-- ═══════════════════════════════════════════════════════════
--  Seed: Professional Loadscreen Templates
--  Run once via MySQL console or oxmysql
-- ═══════════════════════════════════════════════════════════

-- Template 1: "Midnight City" – Dark cinematic loadscreen with gradient, city vibe
INSERT INTO `webcom_loadscreen_designs`
    (`name`, `description`, `canvas_width`, `canvas_height`, `background_color`, `elements`, `is_active`, `is_template`, `created_by`)
VALUES
('Midnight City', 'Dunkle, cinematische Ladeansicht mit Farbverlauf und News-Ticker', 1920, 1080, '#050510', '[
  {"id":"mc01","type":"gradient_overlay","props":{"x":0,"y":0,"width":1920,"height":1080,"zIndex":1,"opacity":1,"visible":true,"gradientType":"linear","gradientAngle":160,"colors":["rgba(10,5,30,0.95)","rgba(5,5,16,0.6)","transparent"],"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc02","type":"particles","props":{"x":0,"y":0,"width":1920,"height":1080,"zIndex":2,"opacity":0.4,"visible":true,"particleCount":60,"particleColor":"#6366f1","particleSize":2,"speed":0.5,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc03","type":"heading_h1","props":{"x":660,"y":280,"width":600,"height":80,"zIndex":10,"opacity":1,"visible":true,"text":"DEIN SERVER","fontSize":56,"fontWeight":"800","fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1.5,"animationDelay":0.3,"animationRepeat":1}},
  {"id":"mc04","type":"paragraph","props":{"x":610,"y":370,"width":700,"height":40,"zIndex":10,"opacity":0.6,"visible":true,"text":"Dein Roleplay-Erlebnis beginnt hier","fontSize":18,"fontWeight":"normal","fontFamily":"Inter","color":"#c4b5fd","textAlign":"center","lineHeight":1.6,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1.5,"animationDelay":0.6,"animationRepeat":1}},
  {"id":"mc05","type":"progress_bar","props":{"x":610,"y":460,"width":700,"height":6,"zIndex":10,"opacity":1,"visible":true,"barColor":"#6366f1","trackColor":"rgba(255,255,255,0.08)","borderRadius":3,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc06","type":"percentage_text","props":{"x":910,"y":478,"width":100,"height":30,"zIndex":10,"opacity":0.5,"visible":true,"fontSize":13,"fontWeight":"600","fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc07","type":"loading_message","props":{"x":610,"y":510,"width":700,"height":24,"zIndex":10,"opacity":0.35,"visible":true,"fontSize":12,"fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc08","type":"social_links","props":{"x":810,"y":960,"width":300,"height":40,"zIndex":10,"opacity":0.5,"visible":true,"links":[],"iconSize":20,"iconColor":"#a78bfa","gap":20,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc09","type":"news_ticker","props":{"x":0,"y":1040,"width":1920,"height":40,"zIndex":15,"opacity":0.8,"visible":true,"items":["Willkommen auf dem Server!","Discord: discord.gg/deinserver","Neue Updates jede Woche"],"fontSize":14,"fontFamily":"Inter","color":"#ffffff","backgroundColor":"rgba(0,0,0,0.6)","scrollSpeed":40,"rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"mc10","type":"glow","props":{"x":760,"y":200,"width":400,"height":400,"zIndex":3,"opacity":0.15,"visible":true,"glowColor":"#6366f1","glowSize":60,"glowIntensity":0.6,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}}
]', 0, 1, 'system');

-- Template 2: "Neon Sidebar" – Left sidebar with player info, right side visual
INSERT INTO `webcom_loadscreen_designs`
    (`name`, `description`, `canvas_width`, `canvas_height`, `background_color`, `elements`, `is_active`, `is_template`, `created_by`)
VALUES
('Neon Sidebar', 'Elegantes Sidebar-Layout mit Spielerinfo und Neon-Akzenten', 1920, 1080, '#080812', '[
  {"id":"ns01","type":"sidebar_panel","props":{"x":0,"y":0,"width":420,"height":1080,"zIndex":5,"opacity":1,"visible":true,"backgroundColor":"rgba(8,8,18,0.92)","rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"slideInLeft","animationDuration":0.8,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns02","type":"neon_border","props":{"x":418,"y":0,"width":4,"height":1080,"zIndex":6,"opacity":0.8,"visible":true,"neonColor":"#22d3ee","neonSize":2,"neonIntensity":0.9,"borderRadius":0,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns03","type":"heading_h2","props":{"x":40,"y":60,"width":340,"height":50,"zIndex":10,"opacity":1,"visible":true,"text":"DEIN SERVER","fontSize":28,"fontWeight":"800","fontFamily":"Inter","color":"#22d3ee","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.2,"animationRepeat":1}},
  {"id":"ns04","type":"divider","props":{"x":40,"y":120,"width":340,"height":1,"zIndex":10,"opacity":0.2,"visible":true,"backgroundColor":"#22d3ee","rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns05","type":"player_name","props":{"x":40,"y":150,"width":340,"height":36,"zIndex":10,"opacity":1,"visible":true,"fontSize":20,"fontWeight":"bold","fontFamily":"Inter","color":"#ffffff","prefix":"Willkommen, ","suffix":"","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.4,"animationRepeat":1}},
  {"id":"ns06","type":"player_playtime","props":{"x":40,"y":196,"width":340,"height":24,"zIndex":10,"opacity":0.5,"visible":true,"fontSize":13,"fontFamily":"Inter","color":"#94a3b8","prefix":"Spielzeit: ","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns07","type":"player_last_login","props":{"x":40,"y":226,"width":340,"height":24,"zIndex":10,"opacity":0.5,"visible":true,"fontSize":13,"fontFamily":"Inter","color":"#94a3b8","prefix":"Letzter Login: ","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns08","type":"divider","props":{"x":40,"y":270,"width":340,"height":1,"zIndex":10,"opacity":0.1,"visible":true,"backgroundColor":"#ffffff","rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns09","type":"rules_list","props":{"x":40,"y":296,"width":340,"height":300,"zIndex":10,"opacity":0.7,"visible":true,"items":["Respektiere alle Spieler","Kein RDM/VDM","RP-Name verwenden","Powergaming verboten","Supportticket bei Problemen"],"fontSize":13,"fontFamily":"Inter","color":"#e2e8f0","numbered":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.6,"animationRepeat":1}},
  {"id":"ns10","type":"progress_bar","props":{"x":40,"y":820,"width":340,"height":8,"zIndex":10,"opacity":1,"visible":true,"barColor":"#22d3ee","trackColor":"rgba(255,255,255,0.06)","borderRadius":4,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns11","type":"percentage_text","props":{"x":40,"y":840,"width":100,"height":24,"zIndex":10,"opacity":0.5,"visible":true,"fontSize":12,"fontWeight":"600","fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns12","type":"loading_message","props":{"x":40,"y":870,"width":340,"height":20,"zIndex":10,"opacity":0.3,"visible":true,"fontSize":11,"fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns13","type":"player_count","props":{"x":40,"y":960,"width":200,"height":30,"zIndex":10,"opacity":0.6,"visible":true,"fontSize":14,"fontWeight":"600","fontFamily":"Inter","color":"#22d3ee","prefix":"","suffix":" Spieler online","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns14","type":"social_links","props":{"x":40,"y":1010,"width":340,"height":36,"zIndex":10,"opacity":0.4,"visible":true,"links":[],"iconSize":18,"iconColor":"#22d3ee","gap":16,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"ns15","type":"particles","props":{"x":420,"y":0,"width":1500,"height":1080,"zIndex":2,"opacity":0.2,"visible":true,"particleCount":30,"particleColor":"#22d3ee","particleSize":2,"speed":0.3,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}}
]', 0, 1, 'system');

-- Template 3: "Clean Minimal" – Centered minimal design, white on dark
INSERT INTO `webcom_loadscreen_designs`
    (`name`, `description`, `canvas_width`, `canvas_height`, `background_color`, `elements`, `is_active`, `is_template`, `created_by`)
VALUES
('Clean Minimal', 'Minimalistisches Design mit zentriertem Logo-Bereich und cleaner Typografie', 1920, 1080, '#0a0a0a', '[
  {"id":"cm01","type":"gradient_overlay","props":{"x":0,"y":0,"width":1920,"height":1080,"zIndex":1,"opacity":1,"visible":true,"gradientType":"radial","gradientAngle":0,"colors":["rgba(20,20,30,0.4)","rgba(10,10,10,1)"],"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cm02","type":"container","props":{"x":660,"y":340,"width":600,"height":400,"zIndex":5,"opacity":1,"visible":true,"backgroundColor":"rgba(255,255,255,0.02)","borderRadius":24,"borderWidth":1,"borderColor":"rgba(255,255,255,0.06)","borderStyle":"solid","rotation":0,"locked":false,"boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1.2,"animationDelay":0,"animationRepeat":1}},
  {"id":"cm03","type":"icon","props":{"x":916,"y":380,"width":88,"height":88,"zIndex":10,"opacity":1,"visible":true,"iconClass":"fa-solid fa-gamepad","color":"#ffffff","fontSize":44,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.2,"animationRepeat":1}},
  {"id":"cm04","type":"heading_h1","props":{"x":710,"y":480,"width":500,"height":60,"zIndex":10,"opacity":1,"visible":true,"text":"SERVER NAME","fontSize":36,"fontWeight":"700","fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.4,"animationRepeat":1}},
  {"id":"cm05","type":"paragraph","props":{"x":760,"y":545,"width":400,"height":30,"zIndex":10,"opacity":0.4,"visible":true,"text":"Roleplay auf einem neuen Level","fontSize":14,"fontWeight":"normal","fontFamily":"Inter","color":"#ffffff","textAlign":"center","lineHeight":1.5,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1,"animationDelay":0.6,"animationRepeat":1}},
  {"id":"cm06","type":"progress_bar","props":{"x":760,"y":620,"width":400,"height":4,"zIndex":10,"opacity":1,"visible":true,"barColor":"#ffffff","trackColor":"rgba(255,255,255,0.08)","borderRadius":2,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cm07","type":"percentage_text","props":{"x":910,"y":636,"width":100,"height":24,"zIndex":10,"opacity":0.3,"visible":true,"fontSize":12,"fontWeight":"500","fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cm08","type":"loading_message","props":{"x":710,"y":670,"width":500,"height":20,"zIndex":10,"opacity":0.2,"visible":true,"fontSize":11,"fontFamily":"Inter","color":"#ffffff","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cm09","type":"player_count","props":{"x":860,"y":1030,"width":200,"height":24,"zIndex":10,"opacity":0.3,"visible":true,"fontSize":12,"fontWeight":"500","fontFamily":"Inter","color":"#ffffff","prefix":"","suffix":" online","textAlign":"center","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}}
]', 0, 1, 'system');

-- Template 4: "Gaming HUD" – Stats cards, header bar, gaming aesthetic
INSERT INTO `webcom_loadscreen_designs`
    (`name`, `description`, `canvas_width`, `canvas_height`, `background_color`, `elements`, `is_active`, `is_template`, `created_by`)
VALUES
('Gaming HUD', 'Gaming-HUD-Stil mit Stat-Karten, Header und dynamischen Elementen', 1920, 1080, '#0c0c14', '[
  {"id":"gh01","type":"gradient_overlay","props":{"x":0,"y":0,"width":1920,"height":1080,"zIndex":1,"opacity":1,"visible":true,"gradientType":"linear","gradientAngle":135,"colors":["rgba(15,10,40,0.9)","rgba(12,12,20,0.7)","rgba(12,12,20,1)"],"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh02","type":"scanlines","props":{"x":0,"y":0,"width":1920,"height":1080,"zIndex":2,"opacity":0.04,"visible":true,"lineSpacing":4,"lineColor":"rgba(0,0,0,0.3)","lineWidth":1,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh03","type":"header_bar","props":{"x":0,"y":0,"width":1920,"height":70,"zIndex":10,"opacity":1,"visible":true,"backgroundColor":"rgba(0,0,0,0.5)","rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"slideInDown","animationDuration":0.6,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh04","type":"heading_h2","props":{"x":40,"y":15,"width":400,"height":40,"zIndex":15,"opacity":1,"visible":true,"text":"DEIN SERVER","fontSize":24,"fontWeight":"800","fontFamily":"Inter","color":"#f59e0b","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh05","type":"player_count","props":{"x":1620,"y":20,"width":260,"height":30,"zIndex":15,"opacity":0.8,"visible":true,"fontSize":15,"fontWeight":"600","fontFamily":"Inter","color":"#f59e0b","prefix":"","suffix":" / 64 Spieler","textAlign":"right","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh06","type":"stat_card","props":{"x":460,"y":380,"width":220,"height":130,"zIndex":10,"opacity":1,"visible":true,"label":"Spieler","value":"0","iconClass":"fa-solid fa-users","color":"#ffffff","accentColor":"#f59e0b","backgroundColor":"rgba(255,255,255,0.04)","borderRadius":16,"borderWidth":1,"borderColor":"rgba(255,255,255,0.06)","rotation":0,"locked":false,"borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":0.8,"animationDelay":0.2,"animationRepeat":1}},
  {"id":"gh07","type":"stat_card","props":{"x":710,"y":380,"width":220,"height":130,"zIndex":10,"opacity":1,"visible":true,"label":"Uptime","value":"--","iconClass":"fa-solid fa-clock","color":"#ffffff","accentColor":"#22c55e","backgroundColor":"rgba(255,255,255,0.04)","borderRadius":16,"borderWidth":1,"borderColor":"rgba(255,255,255,0.06)","rotation":0,"locked":false,"borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":0.8,"animationDelay":0.35,"animationRepeat":1}},
  {"id":"gh08","type":"stat_card","props":{"x":960,"y":380,"width":220,"height":130,"zIndex":10,"opacity":1,"visible":true,"label":"Resources","value":"--","iconClass":"fa-solid fa-cubes","color":"#ffffff","accentColor":"#6366f1","backgroundColor":"rgba(255,255,255,0.04)","borderRadius":16,"borderWidth":1,"borderColor":"rgba(255,255,255,0.06)","rotation":0,"locked":false,"borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":0.8,"animationDelay":0.5,"animationRepeat":1}},
  {"id":"gh09","type":"stat_card","props":{"x":1210,"y":380,"width":220,"height":130,"zIndex":10,"opacity":1,"visible":true,"label":"Queue","value":"--","iconClass":"fa-solid fa-list","color":"#ffffff","accentColor":"#ef4444","backgroundColor":"rgba(255,255,255,0.04)","borderRadius":16,"borderWidth":1,"borderColor":"rgba(255,255,255,0.06)","rotation":0,"locked":false,"borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":0.8,"animationDelay":0.65,"animationRepeat":1}},
  {"id":"gh10","type":"progress_bar","props":{"x":460,"y":570,"width":970,"height":10,"zIndex":10,"opacity":1,"visible":true,"barColor":"#f59e0b","trackColor":"rgba(255,255,255,0.06)","borderRadius":5,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh11","type":"loading_message","props":{"x":460,"y":595,"width":600,"height":24,"zIndex":10,"opacity":0.35,"visible":true,"fontSize":12,"fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh12","type":"percentage_text","props":{"x":1330,"y":595,"width":100,"height":24,"zIndex":10,"opacity":0.5,"visible":true,"fontSize":13,"fontWeight":"bold","fontFamily":"Inter","color":"#f59e0b","textAlign":"right","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh13","type":"tip_carousel","props":{"x":460,"y":660,"width":970,"height":60,"zIndex":10,"opacity":0.5,"visible":true,"tips":["Tipp: Nutze /help fuer eine Befehlsliste","Tipp: Respektiere andere Spieler im RP","Tipp: Benutze Discord fuer Support","Tipp: Neue Features jeden Freitag"],"fontSize":14,"fontFamily":"Inter","color":"#ffffff","interval":4000,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"gh14","type":"footer_bar","props":{"x":0,"y":1010,"width":1920,"height":70,"zIndex":10,"opacity":1,"visible":true,"backgroundColor":"rgba(0,0,0,0.4)","rotation":0,"locked":false,"borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"slideInUp","animationDuration":0.6,"animationDelay":0.1,"animationRepeat":1}},
  {"id":"gh15","type":"social_links","props":{"x":810,"y":1025,"width":300,"height":40,"zIndex":15,"opacity":0.5,"visible":true,"links":[],"iconSize":18,"iconColor":"#f59e0b","gap":20,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}}
]', 0, 1, 'system');

-- Template 5: "Cinematic Widescreen" – Full-screen BG video placeholder, bottom strip
INSERT INTO `webcom_loadscreen_designs`
    (`name`, `description`, `canvas_width`, `canvas_height`, `background_color`, `elements`, `is_active`, `is_template`, `created_by`)
VALUES
('Cinematic Widescreen', 'Kinoformat mit Hintergrund-Video-Bereich, unterer Infostreifen und Letterbox', 1920, 1080, '#000000', '[
  {"id":"cw01","type":"color_overlay","props":{"x":0,"y":0,"width":1920,"height":120,"zIndex":5,"opacity":1,"visible":true,"overlayColor":"#000000","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw02","type":"color_overlay","props":{"x":0,"y":920,"width":1920,"height":160,"zIndex":5,"opacity":1,"visible":true,"overlayColor":"#000000","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw03","type":"gradient_overlay","props":{"x":0,"y":700,"width":1920,"height":380,"zIndex":4,"opacity":1,"visible":true,"gradientType":"linear","gradientAngle":180,"colors":["transparent","rgba(0,0,0,0.9)"],"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw04","type":"heading_h1","props":{"x":80,"y":940,"width":600,"height":50,"zIndex":10,"opacity":1,"visible":true,"text":"DEIN SERVER","fontSize":38,"fontWeight":"800","fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1.5,"animationDelay":0.5,"animationRepeat":1}},
  {"id":"cw05","type":"paragraph","props":{"x":80,"y":990,"width":500,"height":24,"zIndex":10,"opacity":0.5,"visible":true,"text":"Das ultimative Roleplay-Erlebnis","fontSize":14,"fontWeight":"normal","fontFamily":"Inter","color":"#ffffff","textAlign":"left","lineHeight":1.5,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"fadeIn","animationDuration":1.5,"animationDelay":0.8,"animationRepeat":1}},
  {"id":"cw06","type":"progress_bar","props":{"x":80,"y":1040,"width":500,"height":5,"zIndex":10,"opacity":1,"visible":true,"barColor":"#ffffff","trackColor":"rgba(255,255,255,0.12)","borderRadius":3,"animated":true,"rotation":0,"locked":false,"backgroundColor":"transparent","borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw07","type":"percentage_text","props":{"x":80,"y":1052,"width":80,"height":20,"zIndex":10,"opacity":0.4,"visible":true,"fontSize":11,"fontWeight":"600","fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw08","type":"loading_message","props":{"x":170,"y":1052,"width":400,"height":20,"zIndex":10,"opacity":0.25,"visible":true,"fontSize":11,"fontFamily":"Inter","color":"#ffffff","textAlign":"left","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw09","type":"player_count","props":{"x":1650,"y":955,"width":190,"height":28,"zIndex":10,"opacity":0.6,"visible":true,"fontSize":14,"fontWeight":"600","fontFamily":"Inter","color":"#ffffff","prefix":"","suffix":" Spieler online","textAlign":"right","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw10","type":"current_time","props":{"x":1720,"y":990,"width":120,"height":24,"zIndex":10,"opacity":0.3,"visible":true,"fontSize":13,"fontFamily":"Inter","color":"#ffffff","textAlign":"right","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw11","type":"music_player","props":{"x":1560,"y":1030,"width":280,"height":40,"zIndex":10,"opacity":0.4,"visible":true,"trackUrl":"","trackName":"Ambient","autoplay":true,"color":"#ffffff","accentColor":"#ffffff","rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}},
  {"id":"cw12","type":"typewriter_text","props":{"x":80,"y":60,"width":600,"height":40,"zIndex":10,"opacity":0.6,"visible":true,"text":"Verbindung wird hergestellt...","fontSize":16,"fontFamily":"Inter","color":"#ffffff","typeSpeed":60,"loop":false,"rotation":0,"locked":false,"backgroundColor":"transparent","borderRadius":0,"borderWidth":0,"borderColor":"transparent","borderStyle":"solid","boxShadow":"none","overflow":"hidden","animationType":"none","animationDuration":1,"animationDelay":0,"animationRepeat":1}}
]', 0, 1, 'system');
